### ISSUE TITLE
read_team_sheet error

### ISSUE THREAD

**Issue by mmc46** [flyconnectome/tracerutils#50]
I've started getting this error when using the `path` to specify a sheet. It works if I use the `id`.
There isn't another sheet called 'ORN_candidates' in the TeamDrive.

```orn_candidates = read_team_sheet(path = 'ORN_candidates', team_drive = 'flyconnectome', ws = "v2")
Error in add_id_path(nodes, root_id = root_id, leaf = leaf) : 
  !anyDuplicated(nodes$id) is not TRUE
> orn_candidates = read_team_sheet(id = '1MdvjeU6hGpXfKL8BirqEjCTeQnKBnhkZowZU6JE5J60', team_drive = 'flyconnectome', ws = "v2")
Worksheets feed constructed with private visibility
Accessing worksheet titled 'v2'.
Downloading: 21 kB     Parsed with column specification:
cols(
  source = col_double(),
  Checked = col_character(),
  Name = col_character(),
  Verdict = col_character(),
  target_uPN = col_character()
)```

**Comment by mmc46** [comment]
Just to add that this is also the case with the sheet in the example (name updated for current)
```pns <- read_team_sheet('AL_fragments_PN_search', team_drive='flyconnectome',ws=1:2)
Error in add_id_path(nodes, root_id = root_id, leaf = leaf) : 
  !anyDuplicated(nodes$id) is not TRUE

**Comment by jefferis** [comment]
Hi @mmc46,

I get this error:

```
Error in get_team_sheet(path = path, id = id, team_drive = team_drive) : 
  isTRUE(nrow(f) == 1) is not TRUE
```

I don't know where that sheet lives, but the bottom line is that it is not being returned when searching by name. I suspect that this there may have been a change with the google API. It's actually the same if you try to search from the web frontend interactively. I have made a quick update to give better error messages, but I'm afraid the only solution is to use the id.

**Comment by jefferis** [comment]
I'm closing this as it is a limitation of the drive API.
